import { NATIVE_ADMIN_TOKEN_KEY } from './native-admin-auth';
const BASE=(import.meta.env.VITE_PLATFORM_API_URL||'https://postgres-read-api.taxiassur.com/platform').replace(/\/$/,'');
async function call(path:string,init:RequestInit={}){const token=localStorage.getItem(NATIVE_ADMIN_TOKEN_KEY);if(!token)throw new Error('native_session_required');const response=await fetch(`${BASE}${path}`,{...init,cache:'no-store',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...init.headers}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'native_data_error');return data;}
export const nativeAdminDashboard=()=>call('/v1/admin/dashboard');
export const nativeAdminLead=(id:string)=>call(`/v1/admin/leads/${encodeURIComponent(id)}`);
export const nativeAdminUpdateLead=(id:string,updates:Record<string,string|null>)=>call(`/v1/admin/leads/${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify(updates)});
export const nativeAdminDocuments=(status='')=>call(`/v1/admin/documents${status?`?status=${encodeURIComponent(status)}`:''}`);
export const nativeAdminUpdateDocument=(id:string,updates:Record<string,string>)=>call(`/v1/admin/documents/${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify(updates)});
export async function nativeAdminDownloadDocument(id:string,fileName:string){const token=localStorage.getItem(NATIVE_ADMIN_TOKEN_KEY);const response=await fetch(`${BASE}/v1/admin/documents/${encodeURIComponent(id)}/download`,{headers:{Authorization:`Bearer ${token}`}});if(!response.ok)throw new Error('document_unavailable');const url=URL.createObjectURL(await response.blob());const a=document.createElement('a');a.href=url;a.download=fileName||'document';a.click();URL.revokeObjectURL(url);}
export async function nativeAdminDocumentUrl(id:string){const token=localStorage.getItem(NATIVE_ADMIN_TOKEN_KEY);const response=await fetch(`${BASE}/v1/admin/documents/${encodeURIComponent(id)}/download`,{headers:{Authorization:`Bearer ${token}`}});if(!response.ok)throw new Error('document_unavailable');return URL.createObjectURL(await response.blob());}
