import { useEffect, useState } from 'react';
import { AlertCircle, ArrowLeft, CheckCircle, Mail, RefreshCw, ShieldCheck } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { nativeAdminCall, nativeAdminInboxSync } from '@/lib/native-admin-data';

interface EmailAccount { id:string; email:string; imap_host:string; imap_port:number; imap_username:string; smtp_host:string; smtp_port:number; is_active:boolean; password_configured:boolean; last_sync_at:string|null }
type Notice={type:'success'|'error'|'info';text:string};

export default function EmailAccountSettings(){
  const navigate=useNavigate(),[loading,setLoading]=useState(true),[testing,setTesting]=useState(false),[account,setAccount]=useState<EmailAccount|null>(null),[message,setMessage]=useState<Notice|null>(null);
  const loadAccount=async()=>{try{setLoading(true);const data=await nativeAdminCall<{account?:EmailAccount}>('/v1/admin/email-account');setAccount(data.account||null);if(!data.account)setMessage({type:'error',text:'La configuration serveur de la messagerie est introuvable.'});}catch(error){setMessage({type:'error',text:error instanceof Error?error.message:'Erreur lors du chargement'});}finally{setLoading(false);}};
  useEffect(()=>{void loadAccount();},[]);
  const testConnection=async()=>{try{setTesting(true);setMessage({type:'info',text:'Test et synchronisation IMAP en cours...'});const result=await nativeAdminInboxSync() as {success?:boolean;stats?:{emails_retrieved?:number;emails_imported?:number}};if(!result.success)throw new Error('imap_sync_failed');setMessage({type:'success',text:`Connexion réussie : ${result.stats?.emails_retrieved||0} emails trouvés, ${result.stats?.emails_imported||0} synchronisés.`});await loadAccount();}catch(error){setMessage({type:'error',text:error instanceof Error?error.message:'Impossible de tester la connexion'});}finally{setTesting(false);}};
  if(loading)return <div className="min-h-screen bg-slate-900 flex items-center justify-center text-white">Chargement...</div>;
  const fields=account?[['Serveur IMAP',account.imap_host],['Port IMAP',account.imap_port],["Nom d'utilisateur IMAP",account.imap_username],['Serveur SMTP',account.smtp_host],['Port SMTP',account.smtp_port]]:[];
  return <div className="min-h-screen bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900 p-8"><div className="max-w-4xl mx-auto">
    <button onClick={()=>navigate('/backoffice/crm')} className="mb-6 flex items-center gap-2 px-4 py-2 text-slate-300 hover:text-white hover:bg-slate-800/50 rounded-lg"><ArrowLeft size={20}/> Retour</button>
    <div className="mb-8"><h1 className="text-4xl font-bold text-white mb-3">Configuration Email</h1><p className="text-slate-300 text-lg">État de la boîte utilisée pour synchroniser les conversations du CRM</p></div>
    {message&&<div className={`mb-6 p-4 rounded-lg border ${message.type==='success'?'bg-green-900/50 border-green-700 text-green-200':message.type==='error'?'bg-red-900/50 border-red-700 text-red-200':'bg-blue-900/50 border-blue-700 text-blue-200'}`}><div className="flex items-start gap-3">{message.type==='success'?<CheckCircle size={20}/>:message.type==='error'?<AlertCircle size={20}/>:<RefreshCw size={20} className="animate-spin"/>}<span>{message.text}</span></div></div>}
    {account&&<div className="bg-slate-800/50 border border-slate-700 rounded-xl p-6 space-y-6">
      <div className="flex items-center gap-3 pb-4 border-b border-slate-700"><Mail className="text-blue-400" size={24}/><div><h2 className="text-xl font-semibold text-white">{account.email}</h2><p className={account.is_active?'text-green-400':'text-red-400'}>{account.is_active?'Configuration active':'Configuration incomplète'}</p>{account.last_sync_at&&<p className="text-sm text-slate-400">Dernière synchronisation : {new Date(account.last_sync_at).toLocaleString('fr-FR')}</p>}</div></div>
      <div className="grid sm:grid-cols-2 gap-4">{fields.map(([label,value])=><div key={String(label)}><label className="block text-sm font-medium text-slate-300 mb-2">{label}</label><div className="px-4 py-2 bg-slate-900/50 border border-slate-600 rounded-lg text-slate-300">{String(value||'Non configuré')}</div></div>)}<div><label className="block text-sm font-medium text-slate-300 mb-2">Identifiant secret</label><div className="flex items-center gap-2 px-4 py-2 bg-slate-900/50 border border-slate-600 rounded-lg text-slate-300"><ShieldCheck size={18} className={account.password_configured?'text-green-400':'text-red-400'}/>{account.password_configured?'Configuré sur le serveur':'Absent du serveur'}</div></div></div>
      <button onClick={testConnection} disabled={testing||!account.password_configured} className="flex items-center gap-2 px-6 py-3 bg-green-600 hover:bg-green-700 text-white rounded-lg font-medium disabled:opacity-50"><RefreshCw size={20} className={testing?'animate-spin':''}/>{testing?'Test en cours...':'Tester et synchroniser'}</button>
    </div>}
    <div className="mt-6 bg-slate-800/50 border border-slate-700 rounded-xl p-6"><h3 className="text-lg font-semibold text-white mb-3">Sécurité</h3><ul className="text-sm text-slate-300 space-y-2"><li>Le mot de passe IMAP reste exclusivement dans la configuration protégée du serveur.</li><li>Le navigateur ne peut ni lire ni modifier le secret.</li><li>La connexion IMAP utilise TLS sur le port configuré.</li></ul></div>
  </div></div>;
}
