import { useState } from 'react';
import { KeyRound, ShieldCheck } from 'lucide-react';
import { nativeAdminChangePassword } from '@/lib/native-admin-auth';

export default function NativePasswordSettings(){
  const [current,setCurrent]=useState(''); const [next,setNext]=useState(''); const [confirm,setConfirm]=useState(''); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  async function submit(event:React.FormEvent){event.preventDefault();setError('');if(next!==confirm){setError('Les deux nouveaux mots de passe ne correspondent pas.');return;}setBusy(true);try{await nativeAdminChangePassword(current,next);window.location.href='/backoffice';}catch(err){const message=err instanceof Error?err.message:'';setError(message.includes('weak_password')?'Utilisez au moins 14 caractères avec majuscule, minuscule, chiffre et symbole.':'Mot de passe actuel incorrect ou session expirée.');}finally{setBusy(false);}}
  return <div className="max-w-xl mx-auto p-6"><div className="bg-white rounded-2xl border border-gray-200 shadow-sm p-7"><div className="flex items-center gap-3 mb-6"><div className="p-3 rounded-xl bg-amber-100 text-amber-700"><KeyRound/></div><div><h1 className="text-2xl font-bold text-gray-900">Mot de passe local</h1><p className="text-sm text-gray-500">Authentification PostgreSQL TaxiAssur</p></div></div><form onSubmit={submit} className="space-y-4">{error&&<div className="p-3 rounded-lg bg-red-50 text-red-700 text-sm">{error}</div>}<input required type="password" autoComplete="current-password" value={current} onChange={e=>setCurrent(e.target.value)} placeholder="Mot de passe actuel" className="w-full border rounded-lg px-4 py-3"/><input required type="password" autoComplete="new-password" value={next} onChange={e=>setNext(e.target.value)} placeholder="Nouveau mot de passe" className="w-full border rounded-lg px-4 py-3"/><input required type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="Confirmer le nouveau mot de passe" className="w-full border rounded-lg px-4 py-3"/><p className="text-xs text-gray-500 flex gap-2"><ShieldCheck size={16}/>14 caractères minimum, avec majuscule, minuscule, chiffre et symbole.</p><button disabled={busy} className="w-full rounded-lg bg-amber-500 hover:bg-amber-600 disabled:opacity-50 text-white font-semibold py-3">{busy?'Modification…':'Modifier le mot de passe'}</button></form></div></div>;
}
