/*
  # Ajout 200+ Villes Françaises - Couverture Nationale SEO

  ## Objectif
  Ajouter 200+ villes stratégiques pour domination SEO nationale
  "assurance taxi [ville]" dans toute la France

  ## Données Réelles
  - Populations INSEE officielles
  - Calcul taxi_count réaliste (1 taxi / 800 habitants)
  - Départements et régions exacts
*/

-- Insérer les villes avec TOUTES les colonnes requises
INSERT INTO city_pages (city, title, slug, dept, region, population, taxi_count, status, published, created_at) VALUES

-- ÎLE-DE-FRANCE (+40)
('Nogent-sur-Marne', 'Assurance Taxi à Nogent-sur-Marne (94)', 'assurance-taxi-nogent-sur-marne', '94', 'Île-de-France', 31680, 39, 'published', true, NOW()),
('Vincennes', 'Assurance Taxi à Vincennes (94)', 'assurance-taxi-vincennes', '94', 'Île-de-France', 49724, 61, 'published', true, NOW()),
('Fontenay-sous-Bois', 'Assurance Taxi à Fontenay-sous-Bois (94)', 'assurance-taxi-fontenay-sous-bois', '94', 'Île-de-France', 52734, 65, 'published', true, NOW()),
('Saint-Mandé', 'Assurance Taxi à Saint-Mandé (94)', 'assurance-taxi-saint-mande', '94', 'Île-de-France', 23290, 29, 'published', true, NOW()),
('Alfortville', 'Assurance Taxi à Alfortville (94)', 'assurance-taxi-alfortville', '94', 'Île-de-France', 45627, 56, 'published', true, NOW()),
('Charenton-le-Pont', 'Assurance Taxi à Charenton-le-Pont (94)', 'assurance-taxi-charenton-le-pont', '94', 'Île-de-France', 30654, 38, 'published', true, NOW()),
('Le Kremlin-Bicêtre', 'Assurance Taxi au Kremlin-Bicêtre (94)', 'assurance-taxi-le-kremlin-bicetre', '94', 'Île-de-France', 26424, 32, 'published', true, NOW()),
('Villejuif', 'Assurance Taxi à Villejuif (94)', 'assurance-taxi-villejuif', '94', 'Île-de-France', 60129, 74, 'published', true, NOW()),
('Cachan', 'Assurance Taxi à Cachan (94)', 'assurance-taxi-cachan', '94', 'Île-de-France', 30955, 38, 'published', true, NOW()),
('L''Haÿ-les-Roses', 'Assurance Taxi à L''Haÿ-les-Roses (94)', 'assurance-taxi-l-hay-les-roses', '94', 'Île-de-France', 31534, 39, 'published', true, NOW()),

('Suresnes', 'Assurance Taxi à Suresnes (92)', 'assurance-taxi-suresnes', '92', 'Île-de-France', 48565, 60, 'published', true, NOW()),
('Puteaux', 'Assurance Taxi à Puteaux (92)', 'assurance-taxi-puteaux', '92', 'Île-de-France', 44941, 55, 'published', true, NOW()),
('Gennevilliers', 'Assurance Taxi à Gennevilliers (92)', 'assurance-taxi-gennevilliers', '92', 'Île-de-France', 47991, 59, 'published', true, NOW()),
('Clichy', 'Assurance Taxi à Clichy (92)', 'assurance-taxi-clichy', '92', 'Île-de-France', 61343, 75, 'published', true, NOW()),
('Châtenay-Malabry', 'Assurance Taxi à Châtenay-Malabry (92)', 'assurance-taxi-chatenay-malabry', '92', 'Île-de-France', 33650, 41, 'published', true, NOW()),
('Bagneux', 'Assurance Taxi à Bagneux (92)', 'assurance-taxi-bagneux', '92', 'Île-de-France', 39487, 49, 'published', true, NOW()),
('Montrouge', 'Assurance Taxi à Montrouge (92)', 'assurance-taxi-montrouge', '92', 'Île-de-France', 49674, 61, 'published', true, NOW()),
('Vanves', 'Assurance Taxi à Vanves (92)', 'assurance-taxi-vanves', '92', 'Île-de-France', 27729, 34, 'published', true, NOW()),
('Meudon', 'Assurance Taxi à Meudon (92)', 'assurance-taxi-meudon', '92', 'Île-de-France', 45410, 56, 'published', true, NOW()),
('Sceaux', 'Assurance Taxi à Sceaux (92)', 'assurance-taxi-sceaux', '92', 'Île-de-France', 19679, 24, 'published', true, NOW()),

('Pantin', 'Assurance Taxi à Pantin (93)', 'assurance-taxi-pantin', '93', 'Île-de-France', 59846, 73, 'published', true, NOW()),
('Drancy', 'Assurance Taxi à Drancy (93)', 'assurance-taxi-drancy', '93', 'Île-de-France', 71606, 88, 'published', true, NOW()),
('Bondy', 'Assurance Taxi à Bondy (93)', 'assurance-taxi-bondy', '93', 'Île-de-France', 54088, 66, 'published', true, NOW()),
('Noisy-le-Grand', 'Assurance Taxi à Noisy-le-Grand (93)', 'assurance-taxi-noisy-le-grand', '93', 'Île-de-France', 68071, 83, 'published', true, NOW()),
('Épinay-sur-Seine', 'Assurance Taxi à Épinay-sur-Seine (93)', 'assurance-taxi-epinay-sur-seine', '93', 'Île-de-France', 55135, 68, 'published', true, NOW()),
('Sevran', 'Assurance Taxi à Sevran (93)', 'assurance-taxi-sevran', '93', 'Île-de-France', 50626, 62, 'published', true, NOW()),
('Saint-Ouen-sur-Seine', 'Assurance Taxi à Saint-Ouen-sur-Seine (93)', 'assurance-taxi-saint-ouen-sur-seine', '93', 'Île-de-France', 51326, 63, 'published', true, NOW()),
('Rosny-sous-Bois', 'Assurance Taxi à Rosny-sous-Bois (93)', 'assurance-taxi-rosny-sous-bois', '93', 'Île-de-France', 45815, 56, 'published', true, NOW()),
('Bobigny', 'Assurance Taxi à Bobigny (93)', 'assurance-taxi-bobigny', '93', 'Île-de-France', 54364, 67, 'published', true, NOW()),
('La Courneuve', 'Assurance Taxi à La Courneuve (93)', 'assurance-taxi-la-courneuve', '93', 'Île-de-France', 41161, 51, 'published', true, NOW()),

('Cergy', 'Assurance Taxi à Cergy (95)', 'assurance-taxi-cergy', '95', 'Île-de-France', 68780, 84, 'published', true, NOW()),
('Pontoise', 'Assurance Taxi à Pontoise (95)', 'assurance-taxi-pontoise', '95', 'Île-de-France', 31723, 39, 'published', true, NOW()),
('Garges-lès-Gonesse', 'Assurance Taxi à Garges-lès-Gonesse (95)', 'assurance-taxi-garges-les-gonesse', '95', 'Île-de-France', 41972, 52, 'published', true, NOW()),
('Franconville', 'Assurance Taxi à Franconville (95)', 'assurance-taxi-franconville', '95', 'Île-de-France', 34907, 43, 'published', true, NOW()),
('Ermont', 'Assurance Taxi à Ermont (95)', 'assurance-taxi-ermont', '95', 'Île-de-France', 28406, 35, 'published', true, NOW()),
('Gonesse', 'Assurance Taxi à Gonesse (95)', 'assurance-taxi-gonesse', '95', 'Île-de-France', 27946, 34, 'published', true, NOW()),
('Goussainville', 'Assurance Taxi à Goussainville (95)', 'assurance-taxi-goussainville', '95', 'Île-de-France', 31257, 38, 'published', true, NOW()),
('Villiers-le-Bel', 'Assurance Taxi à Villiers-le-Bel (95)', 'assurance-taxi-villiers-le-bel', '95', 'Île-de-France', 28328, 35, 'published', true, NOW()),
('Taverny', 'Assurance Taxi à Taverny (95)', 'assurance-taxi-taverny', '95', 'Île-de-France', 25811, 32, 'published', true, NOW()),
('Bezons', 'Assurance Taxi à Bezons (95)', 'assurance-taxi-bezons', '95', 'Île-de-France', 29155, 36, 'published', true, NOW()),

-- PROVENCE-ALPES-CÔTE D'AZUR (+30)
('Martigues', 'Assurance Taxi à Martigues (13)', 'assurance-taxi-martigues', '13', 'Provence-Alpes-Côte d''Azur', 48942, 60, 'published', true, NOW()),
('Istres', 'Assurance Taxi à Istres (13)', 'assurance-taxi-istres', '13', 'Provence-Alpes-Côte d''Azur', 44444, 55, 'published', true, NOW()),
('Vitrolles', 'Assurance Taxi à Vitrolles (13)', 'assurance-taxi-vitrolles', '13', 'Provence-Alpes-Côte d''Azur', 34929, 43, 'published', true, NOW()),
('Marignane', 'Assurance Taxi à Marignane (13)', 'assurance-taxi-marignane', '13', 'Provence-Alpes-Côte d''Azur', 35572, 44, 'published', true, NOW()),
('La Ciotat', 'Assurance Taxi à La Ciotat (13)', 'assurance-taxi-la-ciotat', '13', 'Provence-Alpes-Côte d''Azur', 35664, 44, 'published', true, NOW()),
('Miramas', 'Assurance Taxi à Miramas (13)', 'assurance-taxi-miramas', '13', 'Provence-Alpes-Côte d''Azur', 25890, 32, 'published', true, NOW()),
('Gardanne', 'Assurance Taxi à Gardanne (13)', 'assurance-taxi-gardanne', '13', 'Provence-Alpes-Côte d''Azur', 20688, 25, 'published', true, NOW()),
('Cagnes-sur-Mer', 'Assurance Taxi à Cagnes-sur-Mer (06)', 'assurance-taxi-cagnes-sur-mer', '06', 'Provence-Alpes-Côte d''Azur', 51800, 64, 'published', true, NOW()),
('Le Cannet', 'Assurance Taxi au Cannet (06)', 'assurance-taxi-le-cannet', '06', 'Provence-Alpes-Côte d''Azur', 41350, 51, 'published', true, NOW()),
('Menton', 'Assurance Taxi à Menton (06)', 'assurance-taxi-menton', '06', 'Provence-Alpes-Côte d''Azur', 28800, 36, 'published', true, NOW()),
('Saint-Laurent-du-Var', 'Assurance Taxi à Saint-Laurent-du-Var (06)', 'assurance-taxi-saint-laurent-du-var', '06', 'Provence-Alpes-Côte d''Azur', 30174, 37, 'published', true, NOW()),
('Vallauris', 'Assurance Taxi à Vallauris (06)', 'assurance-taxi-vallauris', '06', 'Provence-Alpes-Côte d''Azur', 26808, 33, 'published', true, NOW()),
('Vence', 'Assurance Taxi à Vence (06)', 'assurance-taxi-vence', '06', 'Provence-Alpes-Côte d''Azur', 19300, 24, 'published', true, NOW()),
('Six-Fours-les-Plages', 'Assurance Taxi à Six-Fours-les-Plages (83)', 'assurance-taxi-six-fours-les-plages', '83', 'Provence-Alpes-Côte d''Azur', 34677, 43, 'published', true, NOW()),
('La Garde', 'Assurance Taxi à La Garde (83)', 'assurance-taxi-la-garde', '83', 'Provence-Alpes-Côte d''Azur', 25541, 31, 'published', true, NOW()),
('Saint-Raphaël', 'Assurance Taxi à Saint-Raphaël (83)', 'assurance-taxi-saint-raphael', '83', 'Provence-Alpes-Côte d''Azur', 35042, 43, 'published', true, NOW()),
('Draguignan', 'Assurance Taxi à Draguignan (83)', 'assurance-taxi-draguignan', '83', 'Provence-Alpes-Côte d''Azur', 39890, 49, 'published', true, NOW()),
('Brignoles', 'Assurance Taxi à Brignoles (83)', 'assurance-taxi-brignoles', '83', 'Provence-Alpes-Côte d''Azur', 17621, 22, 'published', true, NOW()),
('Orange', 'Assurance Taxi à Orange (84)', 'assurance-taxi-orange', '84', 'Provence-Alpes-Côte d''Azur', 29561, 36, 'published', true, NOW()),
('Carpentras', 'Assurance Taxi à Carpentras (84)', 'assurance-taxi-carpentras', '84', 'Provence-Alpes-Côte d''Azur', 28798, 36, 'published', true, NOW()),
('Cavaillon', 'Assurance Taxi à Cavaillon (84)', 'assurance-taxi-cavaillon', '84', 'Provence-Alpes-Côte d''Azur', 26090, 32, 'published', true, NOW()),
('Apt', 'Assurance Taxi à Apt (84)', 'assurance-taxi-apt', '84', 'Provence-Alpes-Côte d''Azur', 11942, 15, 'published', true, NOW()),
('Manosque', 'Assurance Taxi à Manosque (04)', 'assurance-taxi-manosque', '04', 'Provence-Alpes-Côte d''Azur', 23221, 29, 'published', true, NOW()),
('Digne-les-Bains', 'Assurance Taxi à Digne-les-Bains (04)', 'assurance-taxi-digne-les-bains', '04', 'Provence-Alpes-Côte d''Azur', 16333, 20, 'published', true, NOW()),
('Briançon', 'Assurance Taxi à Briançon (05)', 'assurance-taxi-briancon', '05', 'Provence-Alpes-Côte d''Azur', 12672, 16, 'published', true, NOW()),
('Embrun', 'Assurance Taxi à Embrun (05)', 'assurance-taxi-embrun', '05', 'Provence-Alpes-Côte d''Azur', 6424, 8, 'published', true, NOW()),
('La Valette-du-Var', 'Assurance Taxi à La Valette-du-Var (83)', 'assurance-taxi-la-valette-du-var', '83', 'Provence-Alpes-Côte d''Azur', 23141, 29, 'published', true, NOW()),
('Ollioules', 'Assurance Taxi à Ollioules (83)', 'assurance-taxi-ollioules', '83', 'Provence-Alpes-Côte d''Azur', 13472, 17, 'published', true, NOW()),
('Sanary-sur-Mer', 'Assurance Taxi à Sanary-sur-Mer (83)', 'assurance-taxi-sanary-sur-mer', '83', 'Provence-Alpes-Côte d''Azur', 16778, 21, 'published', true, NOW()),
('Bandol', 'Assurance Taxi à Bandol (83)', 'assurance-taxi-bandol', '83', 'Provence-Alpes-Côte d''Azur', 8558, 11, 'published', true, NOW()),

-- AUVERGNE-RHÔNE-ALPES (+40)
('Vénissieux', 'Assurance Taxi à Vénissieux (69)', 'assurance-taxi-venissieux', '69', 'Auvergne-Rhône-Alpes', 65681, 81, 'published', true, NOW()),
('Caluire-et-Cuire', 'Assurance Taxi à Caluire-et-Cuire (69)', 'assurance-taxi-caluire-et-cuire', '69', 'Auvergne-Rhône-Alpes', 42555, 52, 'published', true, NOW()),
('Vaulx-en-Velin', 'Assurance Taxi à Vaulx-en-Velin (69)', 'assurance-taxi-vaulx-en-velin', '69', 'Auvergne-Rhône-Alpes', 51497, 63, 'published', true, NOW()),
('Saint-Priest', 'Assurance Taxi à Saint-Priest (69)', 'assurance-taxi-saint-priest', '69', 'Auvergne-Rhône-Alpes', 44413, 55, 'published', true, NOW()),
('Bron', 'Assurance Taxi à Bron (69)', 'assurance-taxi-bron', '69', 'Auvergne-Rhône-Alpes', 41014, 51, 'published', true, NOW()),
('Meyzieu', 'Assurance Taxi à Meyzieu (69)', 'assurance-taxi-meyzieu', '69', 'Auvergne-Rhône-Alpes', 34148, 42, 'published', true, NOW()),
('Rillieux-la-Pape', 'Assurance Taxi à Rillieux-la-Pape (69)', 'assurance-taxi-rillieux-la-pape', '69', 'Auvergne-Rhône-Alpes', 30680, 38, 'published', true, NOW()),
('Décines-Charpieu', 'Assurance Taxi à Décines-Charpieu (69)', 'assurance-taxi-decines-charpieu', '69', 'Auvergne-Rhône-Alpes', 27311, 34, 'published', true, NOW()),
('Oullins', 'Assurance Taxi à Oullins (69)', 'assurance-taxi-oullins', '69', 'Auvergne-Rhône-Alpes', 26402, 32, 'published', true, NOW()),
('Givors', 'Assurance Taxi à Givors (69)', 'assurance-taxi-givors', '69', 'Auvergne-Rhône-Alpes', 19875, 25, 'published', true, NOW()),
('Échirolles', 'Assurance Taxi à Échirolles (38)', 'assurance-taxi-echirolles', '38', 'Auvergne-Rhône-Alpes', 36414, 45, 'published', true, NOW()),
('Fontaine', 'Assurance Taxi à Fontaine (38)', 'assurance-taxi-fontaine', '38', 'Auvergne-Rhône-Alpes', 21716, 27, 'published', true, NOW()),
('Saint-Martin-d''Hères', 'Assurance Taxi à Saint-Martin-d''Hères (38)', 'assurance-taxi-saint-martin-d-heres', '38', 'Auvergne-Rhône-Alpes', 37931, 47, 'published', true, NOW()),
('Voiron', 'Assurance Taxi à Voiron (38)', 'assurance-taxi-voiron', '38', 'Auvergne-Rhône-Alpes', 19918, 25, 'published', true, NOW()),
('Bourgoin-Jallieu', 'Assurance Taxi à Bourgoin-Jallieu (38)', 'assurance-taxi-bourgoin-jallieu', '38', 'Auvergne-Rhône-Alpes', 28331, 35, 'published', true, NOW()),
('Firminy', 'Assurance Taxi à Firminy (42)', 'assurance-taxi-firminy', '42', 'Auvergne-Rhône-Alpes', 16657, 21, 'published', true, NOW()),
('Montbrison', 'Assurance Taxi à Montbrison (42)', 'assurance-taxi-montbrison', '42', 'Auvergne-Rhône-Alpes', 15984, 20, 'published', true, NOW()),
('Rive-de-Gier', 'Assurance Taxi à Rive-de-Gier (42)', 'assurance-taxi-rive-de-gier', '42', 'Auvergne-Rhône-Alpes', 14628, 18, 'published', true, NOW()),
('Riom', 'Assurance Taxi à Riom (63)', 'assurance-taxi-riom', '63', 'Auvergne-Rhône-Alpes', 19079, 24, 'published', true, NOW()),
('Cournon-d''Auvergne', 'Assurance Taxi à Cournon-d''Auvergne (63)', 'assurance-taxi-cournon-d-auvergne', '63', 'Auvergne-Rhône-Alpes', 20052, 25, 'published', true, NOW()),
('Issoire', 'Assurance Taxi à Issoire (63)', 'assurance-taxi-issoire', '63', 'Auvergne-Rhône-Alpes', 14391, 18, 'published', true, NOW()),
('Thiers', 'Assurance Taxi à Thiers (63)', 'assurance-taxi-thiers', '63', 'Auvergne-Rhône-Alpes', 11248, 14, 'published', true, NOW()),
('Seynod', 'Assurance Taxi à Seynod (74)', 'assurance-taxi-seynod', '74', 'Auvergne-Rhône-Alpes', 21972, 27, 'published', true, NOW()),
('Annecy-le-Vieux', 'Assurance Taxi à Annecy-le-Vieux (74)', 'assurance-taxi-annecy-le-vieux', '74', 'Auvergne-Rhône-Alpes', 21227, 26, 'published', true, NOW()),
('Cluses', 'Assurance Taxi à Cluses (74)', 'assurance-taxi-cluses', '74', 'Auvergne-Rhône-Alpes', 17330, 22, 'published', true, NOW()),
('Sallanches', 'Assurance Taxi à Sallanches (74)', 'assurance-taxi-sallanches', '74', 'Auvergne-Rhône-Alpes', 16669, 21, 'published', true, NOW()),
('Rumilly', 'Assurance Taxi à Rumilly (74)', 'assurance-taxi-rumilly', '74', 'Auvergne-Rhône-Alpes', 15934, 20, 'published', true, NOW()),
('Aix-les-Bains', 'Assurance Taxi à Aix-les-Bains (73)', 'assurance-taxi-aix-les-bains', '73', 'Auvergne-Rhône-Alpes', 30825, 38, 'published', true, NOW()),
('Albertville', 'Assurance Taxi à Albertville (73)', 'assurance-taxi-albertville', '73', 'Auvergne-Rhône-Alpes', 19214, 24, 'published', true, NOW()),
('La Motte-Servolex', 'Assurance Taxi à La Motte-Servolex (73)', 'assurance-taxi-la-motte-servolex', '73', 'Auvergne-Rhône-Alpes', 11894, 15, 'published', true, NOW()),
('Romans-sur-Isère', 'Assurance Taxi à Romans-sur-Isère (26)', 'assurance-taxi-romans-sur-isere', '26', 'Auvergne-Rhône-Alpes', 33397, 41, 'published', true, NOW()),
('Montélimar', 'Assurance Taxi à Montélimar (26)', 'assurance-taxi-montelimar', '26', 'Auvergne-Rhône-Alpes', 39415, 49, 'published', true, NOW()),
('Tournon-sur-Rhône', 'Assurance Taxi à Tournon-sur-Rhône (07)', 'assurance-taxi-tournon-sur-rhone', '07', 'Auvergne-Rhône-Alpes', 11235, 14, 'published', true, NOW()),
('Annonay', 'Assurance Taxi à Annonay (07)', 'assurance-taxi-annonay', '07', 'Auvergne-Rhône-Alpes', 16278, 20, 'published', true, NOW()),
('Oyonnax', 'Assurance Taxi à Oyonnax (01)', 'assurance-taxi-oyonnax', '01', 'Auvergne-Rhône-Alpes', 22037, 27, 'published', true, NOW()),
('Belley', 'Assurance Taxi à Belley (01)', 'assurance-taxi-belley', '01', 'Auvergne-Rhône-Alpes', 9256, 12, 'published', true, NOW()),
('Vichy', 'Assurance Taxi à Vichy (03)', 'assurance-taxi-vichy', '03', 'Auvergne-Rhône-Alpes', 24726, 31, 'published', true, NOW()),
('Moulins', 'Assurance Taxi à Moulins (03)', 'assurance-taxi-moulins', '03', 'Auvergne-Rhône-Alpes', 19664, 25, 'published', true, NOW()),
('Cusset', 'Assurance Taxi à Cusset (03)', 'assurance-taxi-cusset', '03', 'Auvergne-Rhône-Alpes', 13527, 17, 'published', true, NOW()),
('Le Puy-en-Velay', 'Assurance Taxi au Puy-en-Velay (43)', 'assurance-taxi-le-puy-en-velay', '43', 'Auvergne-Rhône-Alpes', 18629, 23, 'published', true, NOW()),

-- OCCITANIE (+35)
('Lunel', 'Assurance Taxi à Lunel (34)', 'assurance-taxi-lunel', '34', 'Occitanie', 26385, 33, 'published', true, NOW()),
('Frontignan', 'Assurance Taxi à Frontignan (34)', 'assurance-taxi-frontignan', '34', 'Occitanie', 23165, 29, 'published', true, NOW()),
('Agde', 'Assurance Taxi à Agde (34)', 'assurance-taxi-agde', '34', 'Occitanie', 28677, 36, 'published', true, NOW()),
('Lodève', 'Assurance Taxi à Lodève (34)', 'assurance-taxi-lodeve', '34', 'Occitanie', 7584, 9, 'published', true, NOW()),
('Blagnac', 'Assurance Taxi à Blagnac (31)', 'assurance-taxi-blagnac', '31', 'Occitanie', 24990, 31, 'published', true, NOW()),
('Colomiers', 'Assurance Taxi à Colomiers (31)', 'assurance-taxi-colomiers', '31', 'Occitanie', 39098, 48, 'published', true, NOW()),
('Tournefeuille', 'Assurance Taxi à Tournefeuille (31)', 'assurance-taxi-tournefeuille', '31', 'Occitanie', 28570, 35, 'published', true, NOW()),
('Muret', 'Assurance Taxi à Muret (31)', 'assurance-taxi-muret', '31', 'Occitanie', 26015, 32, 'published', true, NOW()),
('Balma', 'Assurance Taxi à Balma (31)', 'assurance-taxi-balma', '31', 'Occitanie', 17918, 22, 'published', true, NOW()),
('Cugnaux', 'Assurance Taxi à Cugnaux (31)', 'assurance-taxi-cugnaux', '31', 'Occitanie', 18032, 23, 'published', true, NOW()),
('Ramonville-Saint-Agne', 'Assurance Taxi à Ramonville-Saint-Agne (31)', 'assurance-taxi-ramonville-saint-agne', '31', 'Occitanie', 12878, 16, 'published', true, NOW()),
('Saint-Orens-de-Gameville', 'Assurance Taxi à Saint-Orens-de-Gameville (31)', 'assurance-taxi-saint-orens-de-gameville', '31', 'Occitanie', 12264, 15, 'published', true, NOW()),
('Foix', 'Assurance Taxi à Foix (09)', 'assurance-taxi-foix', '09', 'Occitanie', 9613, 12, 'published', true, NOW()),
('Pamiers', 'Assurance Taxi à Pamiers (09)', 'assurance-taxi-pamiers', '09', 'Occitanie', 16163, 20, 'published', true, NOW()),
('Limoux', 'Assurance Taxi à Limoux (11)', 'assurance-taxi-limoux', '11', 'Occitanie', 10180, 13, 'published', true, NOW()),
('Castelnaudary', 'Assurance Taxi à Castelnaudary (11)', 'assurance-taxi-castelnaudary', '11', 'Occitanie', 12318, 15, 'published', true, NOW()),
('Millau', 'Assurance Taxi à Millau (12)', 'assurance-taxi-millau', '12', 'Occitanie', 22064, 28, 'published', true, NOW()),
('Villefranche-de-Rouergue', 'Assurance Taxi à Villefranche-de-Rouergue (12)', 'assurance-taxi-villefranche-de-rouergue', '12', 'Occitanie', 11899, 15, 'published', true, NOW()),
('Alès', 'Assurance Taxi à Alès (30)', 'assurance-taxi-ales', '30', 'Occitanie', 41205, 51, 'published', true, NOW()),
('Bagnols-sur-Cèze', 'Assurance Taxi à Bagnols-sur-Cèze (30)', 'assurance-taxi-bagnols-sur-ceze', '30', 'Occitanie', 18183, 23, 'published', true, NOW()),
('Beaucaire', 'Assurance Taxi à Beaucaire (30)', 'assurance-taxi-beaucaire', '30', 'Occitanie', 16263, 20, 'published', true, NOW()),
('Vauvert', 'Assurance Taxi à Vauvert (30)', 'assurance-taxi-vauvert', '30', 'Occitanie', 11803, 15, 'published', true, NOW()),
('Condom', 'Assurance Taxi à Condom (32)', 'assurance-taxi-condom', '32', 'Occitanie', 6882, 9, 'published', true, NOW()),
('Figeac', 'Assurance Taxi à Figeac (46)', 'assurance-taxi-figeac', '46', 'Occitanie', 9912, 12, 'published', true, NOW()),
('Gourdon', 'Assurance Taxi à Gourdon (46)', 'assurance-taxi-gourdon', '46', 'Occitanie', 4327, 5, 'published', true, NOW()),
('Mende', 'Assurance Taxi à Mende (48)', 'assurance-taxi-mende', '48', 'Occitanie', 12318, 15, 'published', true, NOW()),
('Lourdes', 'Assurance Taxi à Lourdes (65)', 'assurance-taxi-lourdes', '65', 'Occitanie', 13326, 17, 'published', true, NOW()),
('Argelès-Gazost', 'Assurance Taxi à Argelès-Gazost (65)', 'assurance-taxi-argeles-gazost', '65', 'Occitanie', 3051, 4, 'published', true, NOW()),
('Céret', 'Assurance Taxi à Céret (66)', 'assurance-taxi-ceret', '66', 'Occitanie', 7878, 10, 'published', true, NOW()),
('Prades', 'Assurance Taxi à Prades (66)', 'assurance-taxi-prades', '66', 'Occitanie', 6263, 8, 'published', true, NOW()),
('Gaillac', 'Assurance Taxi à Gaillac (81)', 'assurance-taxi-gaillac', '81', 'Occitanie', 15181, 19, 'published', true, NOW()),
('Mazamet', 'Assurance Taxi à Mazamet (81)', 'assurance-taxi-mazamet', '81', 'Occitanie', 10134, 13, 'published', true, NOW()),
('Carmaux', 'Assurance Taxi à Carmaux (81)', 'assurance-taxi-carmaux', '81', 'Occitanie', 9699, 12, 'published', true, NOW()),
('Moissac', 'Assurance Taxi à Moissac (82)', 'assurance-taxi-moissac', '82', 'Occitanie', 12758, 16, 'published', true, NOW()),
('Castelsarrasin', 'Assurance Taxi à Castelsarrasin (82)', 'assurance-taxi-castelsarrasin', '82', 'Occitanie', 14013, 18, 'published', true, NOW()),

-- NOUVELLE-AQUITAINE (+30)
('Mérignac', 'Assurance Taxi à Mérignac (33)', 'assurance-taxi-merignac', '33', 'Nouvelle-Aquitaine', 71363, 88, 'published', true, NOW()),
('Pessac', 'Assurance Taxi à Pessac (33)', 'assurance-taxi-pessac', '33', 'Nouvelle-Aquitaine', 64707, 80, 'published', true, NOW()),
('Talence', 'Assurance Taxi à Talence (33)', 'assurance-taxi-talence', '33', 'Nouvelle-Aquitaine', 43561, 54, 'published', true, NOW()),
('Villenave-d''Ornon', 'Assurance Taxi à Villenave-d''Ornon (33)', 'assurance-taxi-villenave-d-ornon', '33', 'Nouvelle-Aquitaine', 33711, 42, 'published', true, NOW()),
('Bègles', 'Assurance Taxi à Bègles (33)', 'assurance-taxi-begles', '33', 'Nouvelle-Aquitaine', 28567, 35, 'published', true, NOW()),
('Gradignan', 'Assurance Taxi à Gradignan (33)', 'assurance-taxi-gradignan', '33', 'Nouvelle-Aquitaine', 24264, 30, 'published', true, NOW()),
('Cenon', 'Assurance Taxi à Cenon (33)', 'assurance-taxi-cenon', '33', 'Nouvelle-Aquitaine', 24669, 31, 'published', true, NOW()),
('Lormont', 'Assurance Taxi à Lormont (33)', 'assurance-taxi-lormont', '33', 'Nouvelle-Aquitaine', 23435, 29, 'published', true, NOW()),
('Eysines', 'Assurance Taxi à Eysines (33)', 'assurance-taxi-eysines', '33', 'Nouvelle-Aquitaine', 24743, 31, 'published', true, NOW()),
('Artigues-près-Bordeaux', 'Assurance Taxi à Artigues-près-Bordeaux (33)', 'assurance-taxi-artigues-pres-bordeaux', '33', 'Nouvelle-Aquitaine', 8507, 11, 'published', true, NOW()),
('Arcachon', 'Assurance Taxi à Arcachon (33)', 'assurance-taxi-arcachon', '33', 'Nouvelle-Aquitaine', 10758, 13, 'published', true, NOW()),
('Libourne', 'Assurance Taxi à Libourne (33)', 'assurance-taxi-libourne', '33', 'Nouvelle-Aquitaine', 25083, 31, 'published', true, NOW()),
('Bergerac', 'Assurance Taxi à Bergerac (24)', 'assurance-taxi-bergerac', '24', 'Nouvelle-Aquitaine', 27579, 34, 'published', true, NOW()),
('Sarlat-la-Canéda', 'Assurance Taxi à Sarlat-la-Canéda (24)', 'assurance-taxi-sarlat-la-caneda', '24', 'Nouvelle-Aquitaine', 9127, 11, 'published', true, NOW()),
('Saintes', 'Assurance Taxi à Saintes (17)', 'assurance-taxi-saintes', '17', 'Nouvelle-Aquitaine', 25366, 31, 'published', true, NOW()),
('Rochefort', 'Assurance Taxi à Rochefort (17)', 'assurance-taxi-rochefort', '17', 'Nouvelle-Aquitaine', 24252, 30, 'published', true, NOW()),
('Royan', 'Assurance Taxi à Royan (17)', 'assurance-taxi-royan', '17', 'Nouvelle-Aquitaine', 18388, 23, 'published', true, NOW()),
('Cognac', 'Assurance Taxi à Cognac (16)', 'assurance-taxi-cognac', '16', 'Nouvelle-Aquitaine', 18704, 23, 'published', true, NOW()),
('Soyaux', 'Assurance Taxi à Soyaux (16)', 'assurance-taxi-soyaux', '16', 'Nouvelle-Aquitaine', 9230, 12, 'published', true, NOW()),
('Tulle', 'Assurance Taxi à Tulle (19)', 'assurance-taxi-tulle', '19', 'Nouvelle-Aquitaine', 14318, 18, 'published', true, NOW()),
('Parthenay', 'Assurance Taxi à Parthenay (79)', 'assurance-taxi-parthenay', '79', 'Nouvelle-Aquitaine', 10599, 13, 'published', true, NOW()),
('Thouars', 'Assurance Taxi à Thouars (79)', 'assurance-taxi-thouars', '79', 'Nouvelle-Aquitaine', 9984, 12, 'published', true, NOW()),
('Bressuire', 'Assurance Taxi à Bressuire (79)', 'assurance-taxi-bressuire', '79', 'Nouvelle-Aquitaine', 19879, 25, 'published', true, NOW()),
('Châtellerault', 'Assurance Taxi à Châtellerault (86)', 'assurance-taxi-chatellerault', '86', 'Nouvelle-Aquitaine', 31722, 39, 'published', true, NOW()),
('Buxerolles', 'Assurance Taxi à Buxerolles (86)', 'assurance-taxi-buxerolles', '86', 'Nouvelle-Aquitaine', 9965, 12, 'published', true, NOW()),
('Panazol', 'Assurance Taxi à Panazol (87)', 'assurance-taxi-panazol', '87', 'Nouvelle-Aquitaine', 11204, 14, 'published', true, NOW()),
('Saint-Junien', 'Assurance Taxi à Saint-Junien (87)', 'assurance-taxi-saint-junien', '87', 'Nouvelle-Aquitaine', 11069, 14, 'published', true, NOW()),
('Dax', 'Assurance Taxi à Dax (40)', 'assurance-taxi-dax', '40', 'Nouvelle-Aquitaine', 21347, 27, 'published', true, NOW()),
('Biscarrosse', 'Assurance Taxi à Biscarrosse (40)', 'assurance-taxi-biscarrosse', '40', 'Nouvelle-Aquitaine', 14693, 18, 'published', true, NOW()),
('Villeneuve-sur-Lot', 'Assurance Taxi à Villeneuve-sur-Lot (47)', 'assurance-taxi-villeneuve-sur-lot', '47', 'Nouvelle-Aquitaine', 23253, 29, 'published', true, NOW()),

-- HAUTS-DE-FRANCE (+25)
('Villeneuve-d''Ascq', 'Assurance Taxi à Villeneuve-d''Ascq (59)', 'assurance-taxi-villeneuve-d-ascq', '59', 'Hauts-de-France', 61151, 75, 'published', true, NOW()),
('Wattrelos', 'Assurance Taxi à Wattrelos (59)', 'assurance-taxi-wattrelos', '59', 'Hauts-de-France', 41006, 51, 'published', true, NOW()),
('Marcq-en-Barœul', 'Assurance Taxi à Marcq-en-Barœul (59)', 'assurance-taxi-marcq-en-baroeul', '59', 'Hauts-de-France', 39644, 49, 'published', true, NOW()),
('Lambersart', 'Assurance Taxi à Lambersart (59)', 'assurance-taxi-lambersart', '59', 'Hauts-de-France', 28417, 35, 'published', true, NOW()),
('La Madeleine', 'Assurance Taxi à La Madeleine (59)', 'assurance-taxi-la-madeleine', '59', 'Hauts-de-France', 22112, 28, 'published', true, NOW()),
('Mons-en-Barœul', 'Assurance Taxi à Mons-en-Barœul (59)', 'assurance-taxi-mons-en-baroeul', '59', 'Hauts-de-France', 21176, 26, 'published', true, NOW()),
('Hem', 'Assurance Taxi à Hem (59)', 'assurance-taxi-hem', '59', 'Hauts-de-France', 18616, 23, 'published', true, NOW()),
('Lomme', 'Assurance Taxi à Lomme (59)', 'assurance-taxi-lomme', '59', 'Hauts-de-France', 28961, 36, 'published', true, NOW()),
('Anzin', 'Assurance Taxi à Anzin (59)', 'assurance-taxi-anzin', '59', 'Hauts-de-France', 13405, 17, 'published', true, NOW()),
('Denain', 'Assurance Taxi à Denain (59)', 'assurance-taxi-denain', '59', 'Hauts-de-France', 19426, 24, 'published', true, NOW()),
('Cambrai', 'Assurance Taxi à Cambrai (59)', 'assurance-taxi-cambrai', '59', 'Hauts-de-France', 32897, 41, 'published', true, NOW()),
('Maubeuge', 'Assurance Taxi à Maubeuge (59)', 'assurance-taxi-maubeuge', '59', 'Hauts-de-France', 29858, 37, 'published', true, NOW()),
('Wasquehal', 'Assurance Taxi à Wasquehal (59)', 'assurance-taxi-wasquehal', '59', 'Hauts-de-France', 21492, 27, 'published', true, NOW()),
('Faches-Thumesnil', 'Assurance Taxi à Faches-Thumesnil (59)', 'assurance-taxi-faches-thumesnil', '59', 'Hauts-de-France', 18178, 23, 'published', true, NOW()),
('Armentières', 'Assurance Taxi à Armentières (59)', 'assurance-taxi-armentieres', '59', 'Hauts-de-France', 25273, 31, 'published', true, NOW()),
('Liévin', 'Assurance Taxi à Liévin (62)', 'assurance-taxi-lievin', '62', 'Hauts-de-France', 30595, 38, 'published', true, NOW()),
('Hénin-Beaumont', 'Assurance Taxi à Hénin-Beaumont (62)', 'assurance-taxi-henin-beaumont', '62', 'Hauts-de-France', 25965, 32, 'published', true, NOW()),
('Bruay-la-Buissière', 'Assurance Taxi à Bruay-la-Buissière (62)', 'assurance-taxi-bruay-la-buissiere', '62', 'Hauts-de-France', 22088, 28, 'published', true, NOW()),
('Carvin', 'Assurance Taxi à Carvin (62)', 'assurance-taxi-carvin', '62', 'Hauts-de-France', 17461, 22, 'published', true, NOW()),
('Berck', 'Assurance Taxi à Berck (62)', 'assurance-taxi-berck', '62', 'Hauts-de-France', 13833, 17, 'published', true, NOW()),
('Saint-Omer', 'Assurance Taxi à Saint-Omer (62)', 'assurance-taxi-saint-omer', '62', 'Hauts-de-France', 13881, 17, 'published', true, NOW()),
('Longuenesse', 'Assurance Taxi à Longuenesse (62)', 'assurance-taxi-longuenesse', '62', 'Hauts-de-France', 11282, 14, 'published', true, NOW()),
('Creil', 'Assurance Taxi à Creil (60)', 'assurance-taxi-creil', '60', 'Hauts-de-France', 35196, 44, 'published', true, NOW()),
('Nogent-sur-Oise', 'Assurance Taxi à Nogent-sur-Oise (60)', 'assurance-taxi-nogent-sur-oise', '60', 'Hauts-de-France', 19727, 25, 'published', true, NOW()),
('Senlis', 'Assurance Taxi à Senlis (60)', 'assurance-taxi-senlis', '60', 'Hauts-de-France', 15370, 19, 'published', true, NOW())

ON CONFLICT (slug) DO NOTHING;

-- Statistiques
DO $$
DECLARE
  v_total integer;
  v_nouvelles integer;
BEGIN
  SELECT COUNT(*) INTO v_total FROM city_pages;
  SELECT COUNT(*) INTO v_nouvelles FROM city_pages WHERE created_at::date = CURRENT_DATE;

  RAISE NOTICE '✅ Migration 1/2 terminée';
  RAISE NOTICE '📊 Total villes: %', v_total;
  RAISE NOTICE '🆕 Nouvelles: %', v_nouvelles;
END $$;
