DatabaseDirectory F:\TaxiAssur\ClamAV\db
TCPSocket 3310
TCPAddr 127.0.0.1
Foreground yes
LogFile F:\TaxiAssur\Logs\clamd.log
LogTime yes
LogClean no
MaxFileSize 20M
MaxScanSize 20M
StreamMaxLength 20M
ReadTimeout 120
CommandReadTimeout 30
SelfCheck 600
